### ISSUE TITLE
[5.09.32pre1] Fluid pipes dont connect

### ISSUE THREAD

**Issue by Wo0kiee** [Blood-Asp/GT5-Unofficial#1327] opened 2017-12-11 17:09 UTC
Fluid pipes don't connect after closing shutter module with machine controller.
![shutter](https://user-images.githubusercontent.com/33743476/33843529-d814225c-dec7-11e7-9795-026cd5e0fb9f.jpg)

**Comment by draknyte1** [comment] 2017-12-11 17:11
Known issue pipes in .09.32 are broken as fuck.
Probably related or a dupe of #1313.

**Closed as completed** 2017-12-21 20:58 UTC
Labels: In progress
