### ISSUE TITLE
Minor bug:  Kanthal Heating Coil achievement not working

### ISSUE THREAD

**Issue by axlegear** [Blood-Asp/GT5-Unofficial#354] opened 2015-12-08 05:15 UTC
Yep, another.  Kanthal coil achivement won't unlock.

**Comment by Blood-Asp** [comment] 2015-12-08 06:00
Same as dataorbs i know it does work. This time on crafting.

**Comment by Blood-Asp** [comment] 2015-12-09 00:17
works fine for me and all others on my server. also more or less duplicate of #352

**Closed by Blood-Asp** 2015-12-09 00:17 UTC
