### ISSUE TITLE
Server crash with java.lang.OutOfMemoryError: Java heap space in 5.09.28

### ISSUE THREAD

**Issue by Krysinski** [Blood-Asp/GT5-Unofficial#931] opened 2017-03-06 08:47 UTC
Server crash with java.lang.OutOfMemoryError: Java heap space in 5.09.28 when player try to connect (from 3500M with 0 players up to 6900M with one player)
[crash-2017-03-06_11.18.34-server.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/820543/crash-2017-03-06_11.18.34-server.txt)
Tested with 27, about 3500M of memory in use all time with same mods.

**Comment by Krysinski** [comment] 2017-03-06 09:04
I will try to upgrade server core up to *58 and ZombieAw mod up to 1.10 (last for 1.7.10)

**Comment by draknyte1** [comment] 2017-03-06 12:21
Try without thermos. If you can't repeat this with plain forge, it's not really our issue.

**Comment by Krysinski** [comment] 2017-03-07 09:29
1. There is no issue with:
- Thermos-1.7.10-1614-56
- gregtech-5.09.27
- zombieawareness-1.9.6

2. Server crash when player connect
`java.lang.OutOfMemoryError: Java heap space` (over 6000M instead 3500M of memory)
- Thermos-1.7.10-1614-56
- **gregtech-5.09.28**
- zombieawareness-1.9.6

3. Server crash when player connect
`java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:74)
	at ZombieAwareness.ZAUtil.giveRandomSpeedBoost(ZAUtil.java:124)
	...`
- **Thermos-1.7.10-1614-58**
- gregtech-5.09.27
- **zombieawareness-1.10**
So, i try to change ZAmod configs:
- disable in General.cfg `I:zombieRandSpeedBoost=0`
- set to low params performance sensitive settings
After that server run normal.

4. There was no issue for me with:
- **Thermos-1.7.10-1614-58**
- **gregtech-5.09.28**
- **zombieawareness-1.10**
- disabled zombieRandSpeedBoost param in ZombieAwareness/General.cfg
- set to low params performance sensitive settings in ZombieAwareness mod configs
**UPD: still get crash with `java.lang.OutOfMemoryError: Java heap space` when some player try to connect**

P.S. plain forge server wasn't been tested

**Comment by draknyte1** [comment] 2017-03-07 10:18
TRY WITH NORMAL FORGE. 
TRY WITHOUT ZOMBIE AWARENESS. 

ZA is the cause based on your error logs. 

You have been asked or I will close this.

**Comment by Krysinski** [comment] 2017-03-07 11:07
I cant try run a copy of my server with normal forge, there are some restricts on host. I suppose that without  ZA server will run perfect. Its just strange coincidence with ZA bugs and GT*28, so you can close this issue. Maybe this fixed issue will help someone who will get same problem. Thank you.

**Comment by Krysinski** [comment] 2017-03-08 07:18
ZA mod will be removed.

**Comment by Corosauce** [comment] 2017-03-10 05:40
in config/CoroUtil.cfg set chunkCacheOverworldOnly to true to prevent this from happening, an issue with some extra dimensions in some modpacks. Or yeah just remove the mod if you were planning on it for other reasons anyways.

**Closed as completed** 2017-03-22 20:58 UTC
Labels: invalid
