### ISSUE TITLE
Add an Isidedinventory for the Controller Block of Assembly Line and delete inventory from Regulator

### ISSUE THREAD

**Issue by ghost** [Blood-Asp/GT5-Unofficial#882] opened 2017-01-31 15:42 UTC
If player want automate Assembly Line, he must have an opportunity to put and output for example data sticks in controller block. Without this player haven't anyway to automate Assembly Line.
Provided that the ability to load, unload, add the controller Assembly Line of how to work the system. The specifics of the line is such that if the bass input, say of size 3*3(because this is the limit of AE(though the ME-interface provides only 8 slots, but this is enough)) throw things, then run the recipe on the line, the line uses just need at every stage of the ingredients, because of this, the method premises only need flash drives to the controller, it is possible to reduce the number of lines is 8 times(because of the capacity of ME-interface). ME interfaces are connected to the controller, which pushes the right amount of things(just 9 types, as in the inventory of the regulator) to each input, but what would the regulator on the ate on the stack of things of each type that would need the controller turned off its own inventory. Things he will take from the entrance and his equipment will be the equipment to which it connected the entrance. Hence, if ME-interface thrust a card of creation and to establish the maintenance of the required number of items(for a single start line), then the inventory controller because of his lack fill will not, and the line will include items equal to 1 craft.
If someone create modpack or developers will add more uses for Assembly Line we will have method for automate it. But it's stupid to don't realize automation only because it isn't widely used.

**Comment by OvermindDL1** [comment] 2017-01-31 15:56
> delete inventory from Regulator

WhyTF would you want to delete the inventory from the regulator?  It would not be capable or working or anything at that point, as well as breaking a substantial amount of factories!

> Add an Isidedinventory for the Controller Block of Assembly Line

Why haven't you submitted a PR yet?  ;-)

**Comment by codewarrior0** [comment] 2017-01-31 16:25
Isn't this a duplicate of #881?

**Comment by OvermindDL1** [comment] 2017-01-31 16:35
> Isn't this a duplicate of #881?

Entirely yes, I'm unsure why the other one was closed especially if this one is not a PR..

**Comment by ghost** [comment] 2017-02-01 06:07
> Entirely yes, I'm unsure why the other one was closed especially if this one is not a PR..

Because there were too many disputes about "does it need to be automate"

**Comment by ghost** [comment] 2017-02-01 06:14
> WhyTF would you want to delete the inventory from the regulator? It would not be capable or working or anything at that point, as well as breaking a substantial amount of factories!

Player can set the input for the regulator and his inventory will be the one to which you move input. That's need for automation too and don't only for Assembly Line. When you connect regulator to ME-net it will be fill him with the autocraft and it's unforgivable when if it fill regulator with nuclear fuel or expensive components for Assembly Line recipes.

**Comment by OvermindDL1** [comment] 2017-02-01 15:07
> Player can set the input for the regulator and his inventory will be the one to which you move input. That's need for automation too and don't only for Assembly Line. When you connect regulator to ME-net it will be fill him with the autocraft and it's unforgivable when if it fill regulator with nuclear fuel or expensive components for Assembly Line recipes.

Except the regulator can regulator what enters into it as well (at least it used to unless that's broken).  It needs an inventory or every current usage of it breaks.

**Comment by Blood-Asp** [comment] 2017-02-03 17:40
for now there is no way to automate it and the suggested way is not exactly how i would change it. But to add a way for automation is on the todo list so leaving this open would be an dublicate.

**Closed as completed by Blood-Asp** 2017-02-03 17:40 UTC

**Comment by ghost** [comment] 2017-02-05 07:20
This means that you will do an automation for assembly line?

**Comment by ghost** [comment] 2017-02-05 07:59
Can you say when you do automation?

**Comment by Blood-Asp** [comment] 2017-02-05 17:46
Likely adding a extra input hatch to the multiblock for the recipe data. Additionally maybe a way to make cheap single use copys of the recipes that get used up when processing, so no removal is needed afterwards.

Then it would only need to find ways to autocraft with more than 9 stacks. I think that would then need Computers or some annoying tricks with existing autocrafting. But maybe others have better ideas.

But no idea about the timeframe. Somewhere beween a few weeks or months...

**Comment by draknyte1** [comment] 2017-02-05 17:51
Why can't people accept that some things don't need automation and they're lazy? It's not hard to use as is. 

Maybe I'm just not a sucker for AE like a broad majority is and can deal with a bit of manual interaction? *shrug*

Like a real assembly line, you don't rapidly change the product, they're purpose built for singular things, requiring extensive (or in this case minimal) work to convert to a second output product.

**Comment by SapientMC** [comment] 2017-02-05 22:16
> Like a real assembly line, you don't rapidly change the product

Now all recipes for AL are: quantum armor set and some LuV components and nobody needs much of them.
If you add some way to make common components which are needed in large quantity (LV/MV hulls/motors/pistons/arms etc) via AL and make it cheaper then usual recipe - then AL will work like IRL. Large amount of same type products with lowest cost per item.

**Comment by leagris** [comment] 2017-02-05 23:57
The purpose of RL assembly line is not only for massive batch production; but also to chain multiple basic assembly operations into an efficient complex assembly of a final product.
That said, instead of needing HSS frames and other pre-assembled components: The AL shall be able to assemble from raw materials or very basic items like here, HSS rods and screws, circuit parts ....
You can already do batch assembling with setting Processing Arrays with Assembling Machines. And nobody yet complained about Processing Arrays requiring player interaction to change the machines inside its GUI or the layout of buses and hatches :)

So instead of this frivolous request for automation into changing an assembly line purposed recipe. It could be better with playability and real life mimicking to allow any item to be crafted into the Assembled with an Assembly Line very efficiently and auto-regulated supply.

I see the process like this:
1. Scan and create a recipe stick from any craftable item.
2. Insert stick into AL as usual.
3. The Assembly Line retrieve all required ingredients and recipes for ingredients recursively.
4. The Assembly Line could perform the assembly from any of the ingredient stages (intermediate or direct ingredients). Like: If it needs a motor in the recipe; it can also use rods, wires and cables to assemble this intermediate motor ingredient. You may also provide it with wires, rods and molten rubber and it will assemble cables for the motor to assemble the final product.
So, the Assembly Line would be able to work with any material components and fluids down to the lowest raw materials, given it has enough segments with input buses and hatches and enough of each material components.
