### ISSUE TITLE
[Quite a big bug] Mk2 reactions consuming 2x fuel, Mk3 4x fuel

### ISSUE THREAD

**Issue by AiwendilCiunio** [Blood-Asp/GT5-Unofficial#181] opened 2015-09-14 20:50 UTC
According to wiki (and NEI) it's supposed to draw 375mb deuterium and 16mb molten beryllium each 16 ticks. 
I tested this with fluid regulators feeding the reactor just a tiny bit more than needed (so 469mb deuterium per second and 21mb molten beryllium per second). If fuel consumption was correct, the amount in input hatches should slowly rise.
It didn't. Both deuterium and beryllium supplies dropped quite quickly and reactor stopped running.
I measured the consumption with a stopwatch and I turns out it uses 2x more fuel than stated, so about
750mb deuterium and 32 molten beryllium each 16 ticks.

:(( 

Please someone test that to confirm, but I'm positive this is happening since I used my old deuterium setup from mk1 (which can output 625mb each 16 ticks) and to my surprise deuterium was running out..

**Comment by Blood-Asp** [comment] 2015-09-14 20:57
Does it also return double the amount of plasma? If yes, do you maybe have an MK3 fusion reactor? Higher tier doubles troughput.

**Comment by AiwendilCiunio** [comment] 2015-09-14 21:07
No, I don't even have americium yet. Both controller and casings are MK2.
Maybe the recipe is registered as mk1 by mistake?

**Comment by AiwendilCiunio** [comment] 2015-09-14 23:27
Yes, it outputs double the amount of plasma - in facts it outputs 2 portions of 175mb almost instantly.

I also checked the other mk2 recipe (lithium-aluminium) and it also draws fuel 2x faster than it should.

So looks like something is fucked up in the code.

**Comment by AiwendilCiunio** [comment] 2015-09-15 12:16
I tested Mk3, and as I expected, it consumes 4x as much fuel.

So something is really broken.

**Comment by AiwendilCiunio** [comment] 2015-09-15 15:47
So, no suggestion what's going on and how it can be fixed?

**Comment by PaladinOne** [comment] 2015-09-15 16:08
[Blood Asp is going to be away at a convention until next Monday.](http://forum.industrial-craft.net/index.php?page=Thread&postID=193238#post193238)

My bet would be that all Fusion recipes are currently being treated as if they were Tier 1, in stead of being split across Tiers 1-3.

**Comment by pyure** [comment] 2015-09-15 17:35
How annoying is it to set up the fusion reactor in creative mode?  I can probably debug this for you before Blood gets back but I've never set up the reactors before.

**Comment by AiwendilCiunio** [comment] 2015-09-15 17:57
2 minutes? I made 2 reactor in sp to test this.

**Comment by pyure** [comment] 2015-09-15 18:04
Thanks;  I'll let you know asap.  May happen tonight (EST)

**Comment by pyure** [comment] 2015-09-16 00:43
Aiwen can you tell me how many hatches of each kind you're using?

**Comment by AiwendilCiunio** [comment] 2015-09-16 07:19
I can't remember now, but why would that matter?

**Comment by pyure** [comment] 2015-09-16 13:03
When Blood did the multiple hatch code on the turbines it needed fixing because the math was off, and I wanted to rule it out.  Doesn't appear to be the case here, but I prefer to test everything.

In this case, I was only able to finish one replication test.  I threw 10 buckets of beryllium and deuterium (each), it processed it nearly instantly and consumed and produced quantities corresponding perfectly to those in the wiki: 16 Molten Beryllium + 375 Deuterium = 175 Nitrogen Plasma

I ran outta time last night but I plan to do a 256 bucket test tonight.

**Comment by AiwendilCiunio** [comment] 2015-09-16 14:44
This is completely not what I reported. 
It's the consumption rate that's completely bugged, treating (probably) each reaction as mk1, hence doubling fuel consumption for mk2 reactions and quadrupling it for mk3.

**Comment by pyure** [comment] 2015-09-16 14:52
Bear with me dude, I parsed your report as best I could, and in any event I gotta put the reactor through all the traces first :)

Now that I have the reactor actually running tonight's work includes (among other things) examining how he's handling the throughput over time.

**Comment by AiwendilCiunio** [comment] 2015-09-16 14:58
In this case, please also test lithium+aluminium reaction. I tested it roughly but it seemed to me that while it consumed 2x as much fuel, it only produced normal amount of sulfur plasma.

**Comment by pyure** [comment] 2015-09-16 15:04
That one's easily reproducible on your end if you don't mind.  Do it in creative and test with a known quantity of input.

**Comment by pyure** [comment] 2015-09-16 19:34
Aiwen, no matter how many times I re-read this thread, I still think I'm missing something.

From what I can tell, the reactor should be consuming 750 Deuterium + 32 Beryllium and producing 350 Nitrogen.

You said "Yes, it outputs double the amount of plasma" so the ratios sound sensible.  You said you tested with a "tiny bit more than needed" for a MK1, but did you test with a "tiny bit more than needed" for a MK2?

**Comment by AiwendilCiunio** [comment] 2015-09-16 20:06
I don't really know how else can I explain this.
Wiki (and NEI) says 16mb molten beryllium and 375mb deuterium every 16 ticks to produce 175mb nitrogen plasma. Right now it consumes 32 molten beryllium and 750mb deuterium every 16 ticks, so twice as fast as it should.

For silicon-magnesium reaction: it should be consuming 16mb molten silicon and 16mb molten magnesium every 32 ticks, but it consumes 64mb molten silicon and 64mb molten magnesium every 32 ticks, so four times as fast.

Which leads me toward the conclusion that all reactions are treated as mk1 reaction (even though the higher tier ones are impossible to perform in lower tier reaction due to energy needed to start).

**Comment by pyure** [comment] 2015-09-16 20:34
Blood asp says "Higher tier doubles troughput. {sic}".  It sounds intended, and the wiki needs updating.  Doubled throughput means he wants the input and output to double.

**Comment by AiwendilCiunio** [comment] 2015-09-16 20:38
No, higher tier than default tier for that reaction. Why even put values in wiki if you have to double or quadruple them at the start? He also asked whether I had MK3 reactor, so he meant that higher tier for mk2 reaction is mk3...

**Comment by pyure** [comment] 2015-09-16 21:35
It wouldn't be the first time GT recipes display the going rate in a way forcing you to do math :)

Ok thanks, using your feedback I've identified a probably culprit.

The process is supposed to execute every 16 ticks for this recipe.  Each time it executes, it resets the progress timer so that it happens X ticks later.  A potential problem is that at the checkRecipe() function, when it determines X, it initialized X to 16 and then divides it by the result of the following:
'public int overclock(int mEUt){
	if(tierOverclock()==1){return 1;}
	if(tierOverclock()==2){return mEUt<32768? 2 : 1;}
	return mEUt<32768?4:mEUt<65536?2:1;
}
'
We're interested in the second clause since this is a tier 2 recipe at 16k eu/t.  In English:

Is this a Tier 2 recipe with less than 32768 eu/t cost?  If so, divide X by 2.

As a result, the 16 tick recipe runs at 8 ticks, subtracting 16/375 each time.

Not 100% sure what Blood wants to accomplish here so I'm not submitting a pull request, but at least he'll know where to look.

**Comment by pyure** [comment] 2015-09-17 13:50
Correction to english-ified version above:
"Is this a Tier 2 reactor running a recipe with less than 32k eu/t cost?"

This explains the problem Aiwen.  At some point Blood must have decided that all Tier 2 recipes were going to start at 32k eu/t.  Anything less than that is considered a Tier 1 recipe.  If you run a Tier 1 recipe in a Tier 2 reactor, we overclock it.  This applies to both reactions you've raised concerns about (the Lithium+Aluminium reaction costs 10k eu/t).

This can be addressed in a million ways but I don't want to screw with his design too much.  Personally I'd add a property to the recipe itself describing it as Tier1,2 etc.

**Comment by willis936** [comment] 2015-09-17 14:22
From a design perspective I'm not sure it's necessary to add a tier field in the recipe list since no other GT5 recipes do that.  You can implicitly figure out the tier by knowing the tier thresholds and the minimum EU/t requirements.  It's necessary to do this for all other machines and multiblocks and I don't see why the fusion reactor should be treated as a special case in this instance.

**Comment by pyure** [comment] 2015-09-17 14:32
That's what Blood did, and it appears to be biting him in the ass.  He has recipes designated as Tier 2 in the wiki, and which presumably require Tier 2 technology, but only require Tier 1 power.  Power may not be a good delineating property.

**Comment by AiwendilCiunio** [comment] 2015-09-17 15:18
Except power usage doesn't indicate tier.
Tier can be indicated by power required to start the reaction.
Max amount you can store in reaction is:
-mk1 - 160m EU
-mk2 - 320m EU
-mk3 - 640m EU
Note that none of higher tier recipes is executable in a lower tier reactor, because of this.

Basically the method currently used to recognize tier is broken. It would be better if it checked for startup EU required, so everything below 160m is mk1, between 161-320 is mk2, between 321-640 is mk3.

**Comment by pyure** [comment] 2015-09-17 15:37
"Except power usage doesn't indicate tier."
What I'm telling you is that it does.  It probably SHOULDN'T, but right now, it does.  A tier 2 recipe starts at 32k,period.  The recipe you're looking at is, by code, a Tier 1 recipe that can only be run in a Tier 2 reactor.  

A glance at the graph suggests your startup cost method would be more sensible.

**Comment by AiwendilCiunio** [comment] 2015-09-17 15:49
Ok I should have put it like this:
"Except power usage shouldn't indicate tier" :)

**Comment by pyure** [comment] 2015-09-17 16:00
In my opinion, precisely.  We need to wait till Blood gets back and explains how he wants it to work.

**Comment by willis936** [comment] 2015-09-20 13:10
If tooltips get updated:

Can the cycle time be changed to ticks from seconds?  "< 1 secs" is not good enough for designing fuel production.  In my opinion it shouldn't be necessary to use external resources for this since there's already a field in a gui to give the information.

**Comment by Blood-Asp** [comment] 2015-09-22 16:59
Should be easy to fix. You guys found out the faulty code corretly, using the startup energy as MK1 = <160m, mk3 = >320m should make everything work correctly.

**Comment by AiwendilCiunio** [comment] 2015-09-25 11:23
Any ETA on the fix? I won't deny that I'd like to finally run my fusion properly :)

**Comment by Blood-Asp** [comment] 2015-09-25 11:44
I'm currently working on new content for GT5.09.  Bugfixing comes once i'm done there. Realistic for that is at last one week before the next bugfix update.

**Closed** 2015-10-03 13:13 UTC
Labels: bug, FixedInDev
