### ISSUE TITLE
Smelting of some dusts changed

### ISSUE THREAD

**Issue by Blood-Asp** [Blood-Asp/GT5-Unofficial#657] opened 2016-09-28 20:47 UTC
For example magnetite dust now smelts into 3 iron nuggets.
Before it was only possible to electrolyze or blast furnace them.

**Comment by mura3277** [comment] 2016-09-29 03:05
Looks like it changed in the LoadTimes PR. The recipes like the Magnetite dust > 10 iron nuggets seems to be fixed by c283f7f

Edit: Confirmed to be intended

**Closed as completed** 2016-09-29 21:15 UTC
Labels: minor bug
