### ISSUE TITLE
Free tin cell: chemical reactor -> dimethyldichlorosilane

### ISSUE THREAD

**Issue by xxx514** [Blood-Asp/GT5-Unofficial#1325] opened 2017-12-10 12:41 UTC
Found this when upgrading from MV to IV - when chemical reactor is setted up with circuit programed to 11 its creating free dimethyldichlorosilane can without taking any empty. Its not very necessary, but can jam automated line [https://imgur.com/a/GKTQO](url). Im using GT 5.09.31 with IC2 Experimental 2.2.286.

**Comment by draknyte1** [comment] 2017-12-10 12:50
Side effect of Johannes making machines do weird shit with cells and circuits.

**Comment by MauveCloud** [comment] 2017-12-10 16:20
Also, this is a duplicate of #1250, and I think it's fixed in 5.09.32pre1.

**Comment by xxx514** [comment] 2017-12-10 17:05
Ow, I apologise then; didnt find #1250 - therefore closing (duplicated).

**Closed as completed** 2017-12-10 17:06 UTC
