### ISSUE TITLE
Fluid Regulator Cover does not let fluid input or output

### ISSUE THREAD

**Issue by leagris** [Blood-Asp/GT5-Unofficial#502] opened 2016-04-28 12:34 UTC
According to [this piece of code](https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/covers/GT_Cover_FluidRegulator.java#L114-L120); the Fluid Regulator Cover let everything pass (Items, Redstone) except fluids:

``` Java
    public boolean letsFluidIn(byte aSide, int aCoverID, int aCoverVariable, Fluid aFluid, ICoverable aTileEntity) {
        return false;
    }

    public boolean letsFluidOut(byte aSide, int aCoverID, int aCoverVariable, Fluid aFluid, ICoverable aTileEntity) {
        return false;
    }
```

And indeed, I cannot get fluid pipes to connect side with fluid regulator:

![2016-04-28_14 32 24](https://cloud.githubusercontent.com/assets/1111474/14885877/2f09154c-0d4e-11e6-8564-47e503804048.png)

**Comment by Blood-Asp** [comment] 2016-04-28 18:29
that method only means that other types of fluid transfers are not allowed to transfer fluids trough the cover. Only the cover itself does transfer the fluids and does limit it that way. There should be somewere another method that should force the pipe visibly connected. Now the question is, is this connection issue only visual, or does it really not transfer fluids?

**Comment by leagris** [comment] 2016-04-28 18:35
It does not transfer fluids. I use Plasma containment pipes.

**Comment by Blood-Asp** [comment] 2016-04-28 21:59
reminds me, what happens when you put the cover on the pipe and not the input hatch?

**Comment by leagris** [comment] 2016-04-29 00:43
If regulator installed on pipe, Pipe appear connected but can not transfer fluid.

**Comment by leagris** [comment] 2016-05-04 17:15
I have tried every placement but none works.
Regulator on pipe output: Appears connected but plasma is not transmitted
Regulator on pipe input: Appears connected but plasma is not transmitted
Regulator on input hatch: Fluid pipe does not connect, no plasma transmitted
Pump cover (output mode) on pipe output against input hatch with regulator: Appears connected due to pump cover on pipe but no plasma transmitted.
Regulator on back-side of input hatch: Input hatch fills unregulated
Regulator on any other side of input hatch: same...
...

**Comment by DEMOOH** [comment] 2016-07-24 14:06
As i can see it, the problem is that **BaseMetaPipeEntity**(it overrides IGregTechTileEntity -> net.minecraftforge.fluids.IFluidHandler methods)  uses  _letsFluidIn/letsFluidOut_ to decide whether it allowed to fill/drain tank. You might add some manualFill/Drain method with flag to force fluid manipulation and then reuse the code with false flag in usual fill/drain.

Unfortunatly, i can't fix this by myself as i don't have a configured IDE. The reason i came here were some annoying bugs and GitHub itself is enough to make some nobrain fixes. I hope they will be merged some day.

**Comment by leagris** [comment] 2016-09-06 11:57
Could this issue have a bit of love before next release?

**Comment by sig** [comment] 2016-10-11 22:43
Bump. Wasted half an hour to figure why it not doing anything.
Also it behaving weirdly with screwdriver - if placed on one side of tube (say north), hitting with screwdriver increases regulated value, but if on opposite (south), it decreasing it, going to negative values, like
-32L/tick etc..
Btw, is this a feature or bug as well?

**Comment by Blood-Asp** [comment] 2016-10-13 21:35
Can someone test if https://github.com/Blood-Asp/GT5-Unofficial/pull/673 works? Is part of the 5.09.25 release.

**Closed as completed** 2016-11-02 22:46 UTC
Labels: bug, fixed
