### ISSUE TITLE
[5.09.31] Gregtech-NEI crash on a modpack

### ISSUE THREAD

**Issue by Georggi** [Blood-Asp/GT5-Unofficial#1241] opened 2017-10-07 09:46 UTC
https://pastebin.com/gfbg6tBh
Used latest commit available at this time.
Link to modpack if anybody wants to test, only need to update gt there: https://github.com/mineproject/pack

**Comment by Georggi** [comment] 2017-10-08 08:56
OK, GTTweaker doesn't properly handle old recipes it seems, not GT issue I guess.

**Comment by Georggi** [comment] 2017-10-08 10:18
It seems null in output stack for chemical reactor causes this, might be gt issue so I am reopening it.

**Comment by mura3277** [comment] 2018-02-17 04:45
This was quite possible caused by an incorrect recipe. It's possible that it's been fixed now. Feel free to reopen if it's still an issue.

**Closed as completed by mura3277** 2018-02-17 04:45 UTC
