### ISSUE TITLE
[1.10.2] Opening crash

### ISSUE THREAD

**Issue by jaskarth** [Blood-Asp/GT5-Unofficial#926] opened 2017-03-05 18:00 UTC
I'm getting an error whenever I try to load IC2 and GT5U, crash report below:
[crash-2017-03-05_12.47.43-client.txt](https://github.com/Blood-Asp/GT5-Unofficial/files/819590/crash-2017-03-05_12.47.43-client.txt)

**Comment by MauveCloud** [comment] 2017-03-05 18:39
Duplicate of #906.

Use IC2 build 142 or older for now, or Chocohead's patcher from this post (since he updated it a few times based on my feedback since the build he linked in that bug):
http://forum.industrial-craft.net/index.php?page=Thread&postID=206805#post206805

**Comment by draknyte1** [comment] 2017-03-05 20:06
> Due to the issue @Dragon2488 mentioned above, he had me build the latest version for him.
> For anyone interested, here is GT 5.10.41

http://www.mediafire.com/file/pd3ipneyakwfl8o/gregtech-5.10.41.jar

Taken from discord.

**Closed as completed** 2017-03-05 20:08 UTC

**Comment by MauveCloud** [comment] 2017-03-05 20:12
I hope that includes Chocohead's other fixes (e.g. changing getWorld() to getWorldObj() and getLocation() to getPosition()), which do not appear to have been made in the repo yet.

**Comment by draknyte1** [comment] 2017-03-05 20:14
No idea, I simply built it. 
![image](https://cloud.githubusercontent.com/assets/3060479/23590918/25311dae-0234-11e7-8dd8-77ac1f70c76e.jpg)

**Comment by Chocohead** [comment] 2017-03-05 22:03
It doesn't, the fixes I was doing were based off of the 1.10 branch here.

Guess I can make a PR for it. EDIT: #927
