### ISSUE TITLE
Wrong data from first scan via Seismic Prospector

### ISSUE THREAD

**Issue by SapientMC** [Blood-Asp/GT5-Unofficial#787] opened 2016-12-06 18:45 UTC
On new world, generated on latest build.
Seismic Prospector + some explosives, using Data Stick. 0 Oil.

Same Prospector + 2-nd portion of explosives, using another Data Stick. And voila, some amount of Oil found.

It works the same if 2-nd scan made via another Seismic Prospector in same chunk.

Seems like something broken with reading data from chunk for the first time.

**Comment by Timeslice42** [comment] 2016-12-07 23:29
@JasonMcRay Isn't this a dupe of one of your issues?

[Edit] #749 I believe

**Comment by SapientMC** [comment] 2016-12-08 09:19
@Timeslice42 seems so

**Closed as completed** 2016-12-25 19:14 UTC
Labels: minor bug, fixed
